//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.29 at 10:51:30 PM PET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.cibertec.edu.pe/ws/objects", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pe.edu.cibertec.ws.objects;
